### ISSUE TITLE
url crazy overwritten problem

### ISSUE THREAD

**Issue by 0xorz** [SquatPhish/Squatting-Domain-Identification#1]
Hangs-MacBook-Pro:Squatting-Domain-Identification hanghu$ sudo python3 squatting_detect.py gooogle.com google.com
Password:
there is no existing csv from URLcrazy, we begin to generate it
/Users/hanghu/Documents/github/Squatting-Domain-Identification/squatting/urlcrazy-0.5/tld.rb:81: warning: key "2nd_level_registration" is duplicated and overwritten on line 81
/Users/hanghu/Documents/github/Squatting-Domain-Identification/squatting/urlcrazy-0.5/tld.rb:89: warning: key "2nd_level_registration" is duplicated and overwritten on line 89
/Users/hanghu/Documents/github/Squatting-Domain-Identification/squatting/urlcrazy-0.5/tld.rb:91: warning: key "2nd_level_registration" is duplicated and overwritten on line 91
/Users/hanghu/Documents/github/Squatting-Domain-Identification/squatting/urlcrazy-0.5/country.rb:60:in `initialize': No such file or directory @ rb_sysopen - /Users/hanghu/Documents/github/Squatting-Domain-Identification/squatting/urlcrazy-0.5/country-codes.txt (Errno::ENOENT)
	from /Users/hanghu/Documents/github/Squatting-Domain-Identification/squatting/urlcrazy-0.5/country.rb:60:in `open'
	from /Users/hanghu/Documents/github/Squatting-Domain-Identification/squatting/urlcrazy-0.5/country.rb:60:in `startup'
	from ./squatting/urlcrazy-0.5/urlcrazy:630:in `<main>'
The analyzed domain and tld name is:
Domain google
TLD com
gooogle.com is a typo of google.com

What is wrong here???????

https://github.com/leebaird/discover/issues/40

**Comment by ririhedou** [comment]
That is the problem of url-crazy. We build our squatting candidates from URL-crazy and DNSTwist.
Because URL-crazy is not maintained, please just ignore that warning and focus on the final result :bowtie:
